a__model_dir: /eos/home-b/bpinolin/ML_output/VBSOS/em_tight/models/v7
base_dir: /eos/home-b/bpinolin/ML_output/
batch_size: 2048
cols:
- detajj
- eta1
- eta2
- detall
- jetpt1
- jetpt2
- met
- dphill
- dphijj
- Mll
- btag_first
- dR_jl1
- dR_jl2
cut: em_tight
epochs: 3
model_tag: model_sgd
model_version: v7
plot_config: VBSOS
samples_version: v7
test_size: 0.2
train_time: 19.40196681022644
val_size: 0.0
