a__model_dir: /eos/home-b/bpinolin/ML_output/VBSOS/em_tight/models/v4
base_dir: /eos/home-b/bpinolin/ML_output/
batch_size: 2048
cols:
- btag_first
- detajj
- detall
- eta1
- eta2
- jetpt1
- jetpt2
- dphill
- dphijj
- Mll
- met
- dR_jl1
- dR_jl2
cut: em_tight
epochs: 3
model_tag: model_sgd
model_version: v4
plot_config: VBSOS
samples_version: v4
test_size: 0.2
train_time: 18.217108726501465
val_size: 0.0
